#pragma once
#include <queue>
#include <string>
#include <UDRefl/UDRefl.hpp>
#include <json/json.hpp>
#include <magic_enum/magic_enum_utility.hpp>
#include "Object.h"
#include "Common/Math/Maths.h"

namespace nilou {

class FContentManager;
class NPackage;

enum class EClassFlags
{
	None				  = 0x00000000u,
    /** Class is a native class - native interfaces will have CLASS_Native set, but not RF_MarkAsNative */
    Native                = 0x00000080u,
    /** Class was declared directly in C++ and has no boilerplate generated by UnrealHeaderTool */
    Intrinsic             = 0x10000000u,
};
ENUM_CLASS_FLAGS(EClassFlags);

struct FClassRegistryBase
{
    FClassRegistryBase(const std::string& InName, NClass* InSuperClass, EClassFlags InClassFlags, std::function<std::shared_ptr<NObject>()> InDefaultClassConstructor, std::function<void(FArchive&, void*)> InSerializeFunction);

    NClass* Class;

    template<typename T>
    struct TPropertyTraits { using Type = FStructProperty; };

    template<> struct TPropertyTraits<std::string> { using Type = FStrProperty; };
    template<> struct TPropertyTraits<int32> { using Type = FIntProperty; };
    template<> struct TPropertyTraits<bool> { using Type = FBoolProperty; };
    template<> struct TPropertyTraits<float> { using Type = FFloatProperty; };
    template<> struct TPropertyTraits<NObject*> { using Type = FObjectProperty; };
};

template <typename T>
struct TClassRegistry : public FClassRegistryBase
{
};

namespace SerializePrivate {

    enum class EMetaClass { Struct, Object };

    template<EMetaClass MetaClass, typename T>
    struct TSelectSerializeFunction
    {
        static std::function<void(FArchive&, void*)> Select()
        {
            static_assert(MetaClass == EMetaClass::Struct || MetaClass == EMetaClass::Object, "MetaClass must be either Struct or Object");
            if constexpr (MetaClass == EMetaClass::Struct)
            {
                return [](FArchive& Ar, void* Value) { Serialize(Ar, *static_cast<T*>(Value)); };
            }
            else if constexpr (MetaClass == EMetaClass::Object)
            {
                return [](FArchive& Ar, void* Value) {     
                    nlohmann::json& Node = Ar.GetNode();
                    if (Ar.IsLoading())
                    {
                        NObject** ppObject = (NObject**)Value;
                        (*ppObject) = FindObject(Node.get<std::string>());
                    }
                    else 
                    {
                        NObject** ppObject = (NObject**)Value;
                        Node = (*ppObject)->GetPathName();
                    } 
                };
            }
        }
    };
}

#define BEGIN_CLASS_REGISTRY(MetaClass, Class, Super, ClassFlags) \
    template<> \
    struct TClassRegistry<Class> : public FClassRegistryBase \
    { \
        using TClass = Class; \
        TClassRegistry<Class>() : FClassRegistryBase(#Class, Super::StaticClass(), ClassFlags, [](){ return std::make_shared<Class>(); }, \
            SerializePrivate::TSelectSerializeFunction<SerializePrivate::EMetaClass::MetaClass, Class>::Select()) \
        {

#define CLASS_PROPERTY(PropertyName) \
            using PropertyType_##PropertyName = decltype(static_cast<TClass*>(nullptr)->PropertyName); \
            auto Property_##PropertyName = new TPropertyTraits<PropertyType_##PropertyName>::Type(); \
            Property_##PropertyName->Name = #PropertyName; \
            Property_##PropertyName->Offset_Internal = offsetof(TClass, PropertyName); \
            Property_##PropertyName->ElementSize = sizeof(PropertyType_##PropertyName); \
            this->Class->Properties.Add(Property_##PropertyName); \

#define END_CLASS_REGISTRY(Class) \
        } \
    }; \
    TClassRegistry<Class> ClassRegistry_##Class;

class NClass : public NObject
{
public:

    template<typename T>
    friend class TClassRegistry;
    friend class FStructProperty;
    friend class FObjectProperty;

    NClass() = default;

    bool IsChildOf(const NClass *BaseClass) const
    {
        if (BaseClass == nullptr)
        {
            return false;
        }
        bool bResult = false;
        for (const NClass* Temp = this; Temp; Temp = Temp->GetSuperStruct())
        {
            if (Temp == BaseClass)
            {
                bResult = true;
                break;
            }
        }
        return bResult;
    }

    TArray<FProperty*> GetProperties(bool bIncludeSuper) const
    {
        TArray<FProperty*> OutProperties;
        if (bIncludeSuper)
        {
            NClass* SuperClass = GetSuperStruct();
            if (SuperClass)
            {
                OutProperties = SuperClass->GetProperties(bIncludeSuper);
            }
        }
        OutProperties.Append(Properties);
        return OutProperties;
    }

    NClass* GetSuperStruct() const
    {
        return SuperStruct;
    }

    NObject* CreateObject(const std::string& Name, NObject* Outer) const;

    void SetClassFlags(EClassFlags FlagsToAdd)
    {
        EClassFlags OldFlags = EClassFlags::None;
        EClassFlags NewFlags = EClassFlags::None;
        do 
        {
            NewFlags = OldFlags | FlagsToAdd;
        }
        while( !ClassFlags.compare_exchange_weak(OldFlags, NewFlags) );
    }

    void ClearClassFlags(EClassFlags FlagsToClear)
    {
        EClassFlags OldFlags = EClassFlags::None;
        EClassFlags NewFlags = EClassFlags::None;
        do 
        {
            NewFlags = OldFlags & (~FlagsToClear);
        }
        while( !ClassFlags.compare_exchange_weak(OldFlags, NewFlags) );
    }

    bool HasAnyClassFlags(EClassFlags FlagsToCheck) const
    {
        return (ClassFlags & FlagsToCheck) != EClassFlags::None;
    }

    bool HasAllClassFlags(EClassFlags FlagsToCheck) const
    {
        return (ClassFlags & FlagsToCheck) == FlagsToCheck;
    }

private:

    std::atomic<EClassFlags> ClassFlags;

    NClass* SuperStruct = nullptr;

    TArray<FProperty*> Properties;

    std::function<std::shared_ptr<NObject>()> ClassConstructor;

    std::function<void(FArchive&, void*)> SerializeFunction;

    friend class FClassRegistryBase;
    template <typename T>
    friend class TClassRegistry;

};

#if 0
/** Older solution */
// template<typename, typename T>
// struct HasMethodSerialize
// {
//     static_assert(
//         std::integral_constant<T, false>::value,
//         "Second template parameter needs to be of function type.");
// };

// template<typename T, typename TReturn, typename ...TArgs>
// struct HasMethodSerialize<T, TReturn(TArgs...)>
// {
// private:
//     template<typename U>
//     static constexpr auto Check(int) 
//         -> typename std::is_same<decltype(std::declval<U>().Serialize(std::declval<TArgs>()...)), TReturn>::type;
//     template<typename U>
//     static constexpr std::false_type Check(...);
//     typedef decltype(Check<T>(0)) type;
// public:
//     static constexpr bool value = std::is_same<type, std::true_type>::value;
// };

// template<typename, typename T>
// struct HasMethodDeserialize
// {
//     static_assert(
//         std::integral_constant<T, false>::value,
//         "Second template parameter needs to be of function type.");
// };

// template<typename T, typename TReturn, typename ...TArgs>
// struct HasMethodDeserialize<T, TReturn(TArgs...)>
// {
// private:
//     template<typename U>
//     static constexpr auto Check(int) 
//         -> typename std::is_same<decltype(std::declval<U>().Deserialize(std::declval<TArgs>()...)), TReturn>::type;
//     template<typename U>
//     static constexpr std::false_type Check(...);
//     typedef decltype(Check<T>(0)) type;
// public:
//     static constexpr bool value = std::is_same<type, std::true_type>::value;
// };

/** C++ 20 solution */
template<typename T, typename TReturn, typename ...TArgs>
concept HasMethodSerialize = requires {
    { std::declval<T>().Serialize(std::declval<TArgs>()...) } -> std::same_as<TReturn>;
};

template<typename T, typename TReturn, typename ...TArgs>
concept HasMethodDeserialize = requires {
    { std::declval<T>().Deserialize(std::declval<TArgs>()...) } -> std::same_as<TReturn>;
};

template<class T>
concept IsMapType = std::same_as<typename T::value_type, std::pair<const typename T::key_type, typename T::mapped_type>>;

template<class T>
concept IsSetType = std::same_as<typename T::value_type, typename T::key_type>;

template<class T>
concept IsRangeContainerType = requires {
    { std::declval<T>().data() } -> std::same_as<typename T::value_type *>;
};

template<class T>
concept HasMethodResize = requires {
    { std::declval<T>().resize(1) } -> std::same_as<void>;
};

template<typename T>
class TStaticSerializer
{
    using RawT = std::remove_cvref_t<T>;
public:
    static void Serialize(RawT &Object, FArchive& Ar) 
    { 
        if constexpr (std::is_enum_v<RawT>)
            Ar.Node = magic_enum::enum_name(Object);
        else if constexpr (std::is_same_v<T, std::string>)
            Ar.Node = Object;
        else if constexpr (HasMethodSerialize<RawT, void, FArchive&>)
            Object.Serialize(Ar);
        else if constexpr (IsMapType<T>)
        {
            for (auto &[ckey, value] : Object)
            {
                typename T::key_type key = ckey;
                nlohmann::json& Node = Ar.Node.emplace_back();
                FArchive local_Ar_key(Node["key"], Ar);
                TStaticSerializer<typename T::key_type>::Serialize(key, local_Ar_key);
                FArchive local_Ar_value(Node["value"], Ar);
                TStaticSerializer<typename T::mapped_type>::Serialize(value, local_Ar_value);
            }
        }
        else if constexpr (IsRangeContainerType<T>)
        {
            for (int i = 0; i < Object.size(); i++)
            {
                nlohmann::json& Node = Ar.Node.emplace_back();
                FArchive local_Ar(Node, Ar);
                TStaticSerializer<typename T::value_type>::Serialize(Object[i], local_Ar);
            }
        }
        else if constexpr (IsSetType<T>)
        {
            for (auto& cvalue : Object)
            {
                using TValue = typename T::value_type;
                TValue value = cvalue;
                nlohmann::json& Node = Ar.Node.emplace_back();
                FArchive local_Ar(Node, Ar);
                TStaticSerializer<TValue>::Serialize(value, local_Ar);
            }
        }
        else 
        {
            Ar.Node = Object;
        }
    }
    static void Deserialize(RawT &Object, FArchive& Ar) 
    { 
        if constexpr (std::is_enum_v<RawT>)
        {
            auto opt = magic_enum::enum_cast<RawT>(Ar.Node.get<std::string>());
            if (opt)
                Object = opt.value();
        }
        else if constexpr (std::is_same_v<T, std::string>)
            Object = Ar.Node.get<RawT>();
        else if constexpr (HasMethodDeserialize<RawT, void, FArchive&>)
            Object.Deserialize(Ar);
        else if constexpr (IsMapType<T>)
        {
            if (Ar.Node.is_array())
            {
                for (int i = 0; i < Ar.Node.size(); i++)
                {
                    nlohmann::json& Node = Ar.Node[i];
                    if (Node.contains("key") && Node.contains("value"))
                    {
                        using TKey = typename T::key_type;
                        using TValue = typename T::mapped_type;
                        TKey key = TKey();
                        TValue value = TValue();
                        FArchive local_Ar_key(Node["key"], Ar);
                        TStaticSerializer<TKey>::Deserialize(key, local_Ar_key);
                        FArchive local_Ar_value(Node["value"], Ar);
                        TStaticSerializer<TValue>::Deserialize(value, local_Ar_value);
                        Object[key] = value;
                    }
                }
            }
        }
        else if constexpr (IsRangeContainerType<T>)
        {
            if (Ar.Node.is_array())
            {
                if constexpr (HasMethodResize<T>)
                    Object.resize(Ar.Node.size());
                for (int i = 0; i < Object.size(); i++)
                {
                    FArchive local_Ar(Ar.Node[i], Ar);
                    TStaticSerializer<typename T::value_type>::Deserialize(Object[i], local_Ar);
                }
            }
        }
        else if constexpr (IsSetType<T>)
        {
            if (Ar.Node.is_array())
            {
                for (int i = 0; i < Ar.Node.size(); i++)
                {
                    using TKey = typename T::key_type;
                    nlohmann::json& Node = Ar.Node[i];
                    TKey key = TKey();
                    FArchive local_Ar(Node, Ar);
                    TStaticSerializer<TKey>::Deserialize(key, local_Ar);
                    Object.insert(key);
                }
            }
        }
        else
        {
            Object = Ar.Node.get<RawT>();
        }
    }
};

template<>
class TStaticSerializer<FBinaryBuffer>
{
public:
    static void Serialize(FBinaryBuffer &Object, FArchive& Ar) 
    { 
        if (Object.BufferSize && Object.Buffer)
        {
            Ar.Node["BufferSize"] = Object.BufferSize;
            Ar.OutBuffers.push_back(FArchiveBuffer(Ar.Node, Object));
        }
    }
    static void Deserialize(FBinaryBuffer &Object, FArchive& Ar) 
    { 
        if (Ar.Node.contains("BufferOffset") && Ar.Node.contains("BufferSize"))
        {
            size_t BufferOffset = Ar.Node["BufferOffset"].get<size_t>();
            Object.BufferSize = Ar.Node["BufferSize"].get<size_t>();
            Object.Buffer = std::make_shared<unsigned char[]>(Object.BufferSize);
            std::copy(
                Ar.InBuffer.get()+BufferOffset, 
                Ar.InBuffer.get()+BufferOffset+Object.BufferSize, 
                Object.Buffer.get());
        }
    }
};
#endif

}