#pragma once
#include <queue>
#include <string>
#include <UDRefl/UDRefl.hpp>
#include <json/json.hpp>
#include <magic_enum/magic_enum_utility.hpp>
#include "Object.h"
#include "Common/Math/Maths.h"

namespace nilou {

class FContentManager;
class NPackage;

enum class EClassFlags
{
	None				  = 0x00000000u,
    /** Class is a native class - native interfaces will have CLASS_Native set, but not RF_MarkAsNative */
    Native                = 0x00000080u,
    /** Class was declared directly in C++ and has no boilerplate generated by UnrealHeaderTool */
    Intrinsic             = 0x10000000u,
};
ENUM_CLASS_FLAGS(EClassFlags);

#if __cplusplus >= 202002L
template <typename T>
concept HasStaticClass = requires {
    { T::StaticClass() } -> std::same_as<NClass*>;
};
template <typename T>
struct THasStaticClass { static constexpr bool Value = HasStaticClass<T>; };

template <typename T>
concept HasStaticEnum = requires {
    { StaticEnum<T>() } -> std::same_as<NClass*>;
};
template <typename T>
struct THasStaticEnum { static constexpr bool Value = HasStaticEnum<T>; };
#else
template <typename T>
struct THasStaticClass 
{ 
private:
    template <typename U>
    static constexpr auto Test(U*) -> decltype(U::StaticClass(), std::true_type{});
    template <typename U>
    static constexpr std::false_type Test(...);
public:
    static constexpr bool Value = decltype(Test<T>(nullptr))::value; 
};

template <typename T>
struct THasStaticEnum 
{ 
private:
    template <typename U>
    static constexpr auto Test(U*) -> decltype(StaticEnum<U>(), std::true_type{});
    template <typename U>
    static constexpr std::false_type Test(...);
public:
    static constexpr bool Value = decltype(Test<T>(nullptr))::value; 
};
#endif

enum class EMetaClass { Struct, Object, Enum };

struct FClassRegistryBase
{
    struct NullSuperClass { static NClass* StaticClass() { return nullptr; } };

    FClassRegistryBase(EMetaClass InMetaClass, const std::string& InName, NClass* InSuperClass, int32 InSize, EClassFlags InClassFlags, std::function<void(void*)> InDefaultClassConstructor);
    
    EMetaClass MetaClass;

    NClass* Class;

    template<typename T> 
    struct TConstructProperty 
    { 
        static FProperty* Construct() 
        {
            if constexpr (std::is_pointer_v<T> && TIsDerivedFrom<std::remove_pointer_t<T>, NObject>::Value)
            {
                return new FObjectProperty;
            }
            else if constexpr (std::is_enum_v<T> && THasStaticEnum<T>::Value)
            {
                FEnumProperty* Property = new FEnumProperty;
                Property->Enum = StaticEnum<T>();
                return Property;
            }
            else if constexpr (THasStaticClass<T>::Value)
            {
                FStructProperty* Property = new FStructProperty;
                Property->Struct = T::StaticClass();
                return Property;
            }
            else 
            {
                static_assert(false, "T is not a supported reflection type.");
                return nullptr;
            }
        } 
    };
    
    template<> struct TConstructProperty<std::string> { static FProperty* Construct() { return new FStrProperty; } };
    template<> struct TConstructProperty<int8> { static FProperty* Construct() { return new FInt8Property; } };
    template<> struct TConstructProperty<int16> { static FProperty* Construct() { return new FInt16Property; } };
    template<> struct TConstructProperty<int32> { static FProperty* Construct() { return new FInt32Property; } };
    template<> struct TConstructProperty<int64> { static FProperty* Construct() { return new FInt64Property; } };
    template<> struct TConstructProperty<uint8> { static FProperty* Construct() { return new FUInt8Property; } };
    template<> struct TConstructProperty<uint16> { static FProperty* Construct() { return new FUInt16Property; } };
    template<> struct TConstructProperty<uint32> { static FProperty* Construct() { return new FUInt32Property; } };
    template<> struct TConstructProperty<uint64> { static FProperty* Construct() { return new FUInt64Property; } };
    template<> struct TConstructProperty<bool> { static FProperty* Construct() { return new FBoolProperty; } };
    template<> struct TConstructProperty<float> { static FProperty* Construct() { return new FFloatProperty; } };
    template<> struct TConstructProperty<double> { static FProperty* Construct() { return new FDoubleProperty; } };
    template<typename T> struct TConstructProperty<TArray<T>>
    { 
        static FProperty* Construct() 
        { 
            FArrayProperty* Property = new FArrayProperty;
            Property->Inner = TConstructProperty<T>::Construct();
            Property->GetNum = [](const void* Array) { return reinterpret_cast<const TArray<T>*>(Array)->Num(); };
            Property->GetItem = [](void* Array, size_t Index) { return &(reinterpret_cast<TArray<T>*>(Array)->GetData()[Index]); };
            Property->ItemIdentical = &FArrayProperty::ItemIdenticalTemplate<T>;
            Property->ItemSerializer = &FArrayProperty::ItemSerializerTemplate<T>;
            return Property;
        } 
    };
    template<typename K, typename V> struct TConstructProperty<TMap<K, V>> 
    { 
        static FProperty* Construct() 
        { 
            FMapProperty* Property = new FMapProperty;
            Property->KeyProp = TConstructProperty<K>::Construct();
            Property->ValueProp = TConstructProperty<V>::Construct();
            Property->GetNum = [](const void* pMap) { return reinterpret_cast<const TMap<K, V>*>(pMap)->Num(); };
            Property->GetPairs = [](const void* pMap) 
            { 
                const TMap<K, V>& Map = *reinterpret_cast<const TMap<K, V>*>(pMap);
                TArray<void*> Pairs;
                for (auto& Pair : Map)
                {
                    Pairs.Add((void*)&Pair);
                }
                return Pairs;
            };
            Property->PairGetKey = [](void* Pair) -> void* { return (void*)&(reinterpret_cast<TMap<K, V>::value_type*>(Pair)->first); };
            Property->PairGetValue = [](void* Pair) -> void* { return &(reinterpret_cast<TMap<K, V>::value_type*>(Pair)->second); };
            Property->ItemIdentical = &FMapProperty::ItemIdenticalTemplate<K, V>;
            Property->ItemSerializer = &FMapProperty::ItemSerializerTemplate<K, V>;
            return Property;
        } 
    };
    template<typename T> struct TConstructProperty<TSet<T>> 
    { 
        static FProperty* Construct() 
        { 
            FSetProperty* Property = new FSetProperty;
            Property->Inner = TConstructProperty<T>::Construct();
            Property->GetItems = [](const void* pSet)
            {
                const TSet<T>& Set = *reinterpret_cast<const TSet<T>*>(pSet);
                TArray<void*> Items;
                for (auto& Item : Set)
                {
                    Items.Add((void*)&Item);
                }
                return Items;
            };
            Property->GetNum = [](const void* Set) { return reinterpret_cast<const TSet<T>*>(Set)->Num(); };
            Property->ItemIdentical = &FSetProperty::ItemIdenticalTemplate<T>;
            Property->ItemSerializer = &FSetProperty::ItemSerializerTemplate<T>;
            return Property;
        } 
    };
    template<typename T> struct TConstructProperty<TVector2<T>> 
    { 
        static FProperty* Construct() 
        { 
            FVectorProperty* Property = new FVectorProperty;
            Property->ItemIdentical = &FVectorProperty::ItemIdenticalTemplate<TVector2<T>>;
            Property->ItemSerializer = &FVectorProperty::ItemSerializerTemplate<TVector2<T>>;
            return Property;
        } 
    };
    template<typename T> struct TConstructProperty<TVector<T>> 
    { 
        static FProperty* Construct() 
        { 
            FVectorProperty* Property = new FVectorProperty;
            Property->ItemIdentical = &FVectorProperty::ItemIdenticalTemplate<TVector<T>>;
            Property->ItemSerializer = &FVectorProperty::ItemSerializerTemplate<TVector<T>>;
            return Property;
        } 
    };
    template<typename T> struct TConstructProperty<TVector4<T>> 
    { 
        static FProperty* Construct() 
        { 
            FVectorProperty* Property = new FVectorProperty;
            Property->ItemIdentical = &FVectorProperty::ItemIdenticalTemplate<TVector4<T>>;
            Property->ItemSerializer = &FVectorProperty::ItemSerializerTemplate<TVector4<T>>;
            return Property;
        } 
    };
    template<typename T> struct TConstructProperty<TQuat<T>> 
    { 
        static FProperty* Construct() 
        { 
            FQuatProperty* Property = new FQuatProperty;
            Property->ItemIdentical = &FQuatProperty::ItemIdenticalTemplate<TQuat<T>>;
            Property->ItemSerializer = &FQuatProperty::ItemSerializerTemplate<TQuat<T>>;
            return Property;
        } 
    };

    template <typename T, typename U>
    size_t offset_of(T U::*Member)
    {
        return reinterpret_cast<size_t>(
            &(reinterpret_cast<U*>(0)->*Member)
        );
    }

    template <typename T, typename U>
    void AddProperty(const std::string& Name, T U::*Member)
    {
        ConstructFProperty.Add([this, Name, Member]() {
            auto Property = TConstructProperty<T>::Construct();
            Property->Name = Name; \
            Property->Offset_Internal = offset_of(Member); \
            Property->ElementSize = sizeof(T); \
            AddProperty(Property);
        });
    }

    void AddProperty(FProperty* Property);

    TArray<std::function<void()>> ConstructFProperty;

    static void DeferredConstructFProperty();

    std::string RemoveNamespace(const std::string& Name);

    std::string RemovePrefix(EMetaClass InMetaClass, const std::string& Name);

};

template <typename T>
struct TClassRegistry : public FClassRegistryBase
{
};

namespace SerializePrivate {

    
}

#define BEGIN_CLASS_REGISTRY_INTERNAL(MetaClass, ClassName, Super, ClassFlags) \
    NClass* ClassName::Z_StaticClass = nullptr; \
    template<> \
    struct TClassRegistry<ClassName> : public FClassRegistryBase \
    { \
        using TClass = ClassName; \
        TClassRegistry<ClassName>() : FClassRegistryBase( \
            EMetaClass::MetaClass, \
            #ClassName, \
            Super::StaticClass(), \
            sizeof(ClassName), \
            ClassFlags, \
            [](void* Memory){ new (Memory) ClassName(); }) \
        { \
            TClass::Z_StaticClass = this->Class;

#define BEGIN_CLASS_REGISTRY(ClassName, Super, ClassFlags) \
    BEGIN_CLASS_REGISTRY_INTERNAL(Object, ClassName, Super, ClassFlags)

#define BEGIN_STRUCT_REGISTRY(ClassName, Super, ClassFlags) \
    BEGIN_CLASS_REGISTRY_INTERNAL(Struct, ClassName, Super, ClassFlags)


#define CLASS_PROPERTY(PropertyName) \
            AddProperty(#PropertyName, &TClass::PropertyName);

#define STRUCT_PROPERTY(PropertyName) CLASS_PROPERTY(PropertyName)

#define END_CLASS_REGISTRY(ClassName) \
        } \
    }; \
    TClassRegistry<ClassName> PREPROCESSOR_JOIN(ClassRegistry, __LINE__);

#define END_STRUCT_REGISTRY(ClassName) END_CLASS_REGISTRY(ClassName)

#define BEGIN_ENUM_REGISTRY(EnumName, ClassFlags) \
    NClass* StaticEnum_##EnumName = nullptr; \
    template<> \
    struct TClassRegistry<EnumName> : public FClassRegistryBase \
    { \
        using TEnum = EnumName; \
        TClassRegistry<EnumName>() : FClassRegistryBase( \
            EMetaClass::Enum, \
            #EnumName, \
            nullptr, \
            sizeof(EnumName), \
            ClassFlags, \
            [](void* Memory){ new (Memory) EnumName(); }) \
        { \
            StaticEnum_##EnumName = this->Class;

#define ENUM_VALUE(Value) \
            this->Class->EnumNames.Add({#Value, static_cast<int64>(TEnum::Value)});

#define END_ENUM_REGISTRY(EnumName) \
        } \
    }; \
    template<> NClass* StaticEnum<EnumName>() { return StaticEnum_##EnumName; } \
    TClassRegistry<EnumName> PREPROCESSOR_JOIN(ClassRegistry, __LINE__);

class NClass : public NObject
{
private:
    template<typename T> 
    friend class TClassRegistry;
    friend class FClassRegistryBase;
    static NClass* Z_StaticClass;
public:
    static NClass *StaticClass() { return Z_StaticClass; }
public:
    friend class FStructProperty;
    friend class FObjectProperty;
    friend class FEnumProperty;
    friend void InitUObject();

    NClass() = default;

    bool IsChildOf(const NClass *BaseClass) const
    {
        if (BaseClass == nullptr)
        {
            return false;
        }
        bool bResult = false;
        for (const NClass* Temp = this; Temp; Temp = Temp->GetSuperStruct())
        {
            if (Temp == BaseClass)
            {
                bResult = true;
                break;
            }
        }
        return bResult;
    }

    TArray<FProperty*> GetProperties(bool bIncludeSuper) const;

    void SerializeTaggedProperties(FArchive& Ar, void* Data) const;

    bool IdenticalProperties(const void* A, const void* B) const;

    NClass* GetSuperStruct() const
    {
        return SuperStruct;
    }

    NObject* CreateObject(const std::string& Name, NObject* Outer) const;

    void SetClassFlags(EClassFlags FlagsToAdd)
    {
        EClassFlags OldFlags = EClassFlags::None;
        EClassFlags NewFlags = EClassFlags::None;
        do 
        {
            NewFlags = OldFlags | FlagsToAdd;
        }
        while( !ClassFlags.compare_exchange_weak(OldFlags, NewFlags) );
    }

    void ClearClassFlags(EClassFlags FlagsToClear)
    {
        EClassFlags OldFlags = EClassFlags::None;
        EClassFlags NewFlags = EClassFlags::None;
        do 
        {
            NewFlags = OldFlags & (~FlagsToClear);
        }
        while( !ClassFlags.compare_exchange_weak(OldFlags, NewFlags) );
    }

    bool HasAnyClassFlags(EClassFlags FlagsToCheck) const
    {
        return (ClassFlags & FlagsToCheck) != EClassFlags::None;
    }

    bool HasAllClassFlags(EClassFlags FlagsToCheck) const
    {
        return (ClassFlags & FlagsToCheck) == FlagsToCheck;
    }

    NObject* GetDefaultObject() const;
    template <typename T>
    T* GetDefaultObject() const { return Cast<T>(GetDefaultObject()); }

    int64 GetValueByNameString(const std::string& Name) const;
    std::string GetNameStringByValue(int64 Value) const;

protected:
    void CreateDefaultObject();

private:

    int32 Size;

    EMetaClass MetaClass;

    std::atomic<EClassFlags> ClassFlags;

    NClass* SuperStruct = nullptr;

    TArray<FProperty*> Properties;

	TArray<std::pair<std::string, int64>> EnumNames;

    std::function<void(void*)> ClassConstructor;

    NObject* ClassDefaultObject;

};

template <typename T> NClass* StaticEnum();

#if 0
/** Older solution */
// template<typename, typename T>
// struct HasMethodSerialize
// {
//     static_assert(
//         std::integral_constant<T, false>::value,
//         "Second template parameter needs to be of function type.");
// };

// template<typename T, typename TReturn, typename ...TArgs>
// struct HasMethodSerialize<T, TReturn(TArgs...)>
// {
// private:
//     template<typename U>
//     static constexpr auto Check(int) 
//         -> typename std::is_same<decltype(std::declval<U>().Serialize(std::declval<TArgs>()...)), TReturn>::type;
//     template<typename U>
//     static constexpr std::false_type Check(...);
//     typedef decltype(Check<T>(0)) type;
// public:
//     static constexpr bool value = std::is_same<type, std::true_type>::value;
// };

// template<typename, typename T>
// struct HasMethodDeserialize
// {
//     static_assert(
//         std::integral_constant<T, false>::value,
//         "Second template parameter needs to be of function type.");
// };

// template<typename T, typename TReturn, typename ...TArgs>
// struct HasMethodDeserialize<T, TReturn(TArgs...)>
// {
// private:
//     template<typename U>
//     static constexpr auto Check(int) 
//         -> typename std::is_same<decltype(std::declval<U>().Deserialize(std::declval<TArgs>()...)), TReturn>::type;
//     template<typename U>
//     static constexpr std::false_type Check(...);
//     typedef decltype(Check<T>(0)) type;
// public:
//     static constexpr bool value = std::is_same<type, std::true_type>::value;
// };

/** C++ 20 solution */
template<typename T, typename TReturn, typename ...TArgs>
concept HasMethodSerialize = requires {
    { std::declval<T>().Serialize(std::declval<TArgs>()...) } -> std::same_as<TReturn>;
};

template<typename T, typename TReturn, typename ...TArgs>
concept HasMethodDeserialize = requires {
    { std::declval<T>().Deserialize(std::declval<TArgs>()...) } -> std::same_as<TReturn>;
};

template<class T>
concept IsMapType = std::same_as<typename T::value_type, std::pair<const typename T::key_type, typename T::mapped_type>>;

template<class T>
concept IsSetType = std::same_as<typename T::value_type, typename T::key_type>;

template<class T>
concept IsRangeContainerType = requires {
    { std::declval<T>().data() } -> std::same_as<typename T::value_type *>;
};

template<class T>
concept HasMethodResize = requires {
    { std::declval<T>().resize(1) } -> std::same_as<void>;
};

template<typename T>
class TStaticSerializer
{
    using RawT = std::remove_cvref_t<T>;
public:
    static void Serialize(RawT &Object, FArchive& Ar) 
    { 
        if constexpr (std::is_enum_v<RawT>)
            Ar.Node = magic_enum::enum_name(Object);
        else if constexpr (std::is_same_v<T, std::string>)
            Ar.Node = Object;
        else if constexpr (HasMethodSerialize<RawT, void, FArchive&>)
            Object.Serialize(Ar);
        else if constexpr (IsMapType<T>)
        {
            for (auto &[ckey, value] : Object)
            {
                typename T::key_type key = ckey;
                nlohmann::json& Node = Ar.Node.emplace_back();
                FArchive local_Ar_key(Node["key"], Ar);
                TStaticSerializer<typename T::key_type>::Serialize(key, local_Ar_key);
                FArchive local_Ar_value(Node["value"], Ar);
                TStaticSerializer<typename T::mapped_type>::Serialize(value, local_Ar_value);
            }
        }
        else if constexpr (IsRangeContainerType<T>)
        {
            for (int i = 0; i < Object.size(); i++)
            {
                nlohmann::json& Node = Ar.Node.emplace_back();
                FArchive local_Ar(Node, Ar);
                TStaticSerializer<typename T::value_type>::Serialize(Object[i], local_Ar);
            }
        }
        else if constexpr (IsSetType<T>)
        {
            for (auto& cvalue : Object)
            {
                using TValue = typename T::value_type;
                TValue value = cvalue;
                nlohmann::json& Node = Ar.Node.emplace_back();
                FArchive local_Ar(Node, Ar);
                TStaticSerializer<TValue>::Serialize(value, local_Ar);
            }
        }
        else 
        {
            Ar.Node = Object;
        }
    }
    static void Deserialize(RawT &Object, FArchive& Ar) 
    { 
        if constexpr (std::is_enum_v<RawT>)
        {
            auto opt = magic_enum::enum_cast<RawT>(Ar.Node.get<std::string>());
            if (opt)
                Object = opt.value();
        }
        else if constexpr (std::is_same_v<T, std::string>)
            Object = Ar.Node.get<RawT>();
        else if constexpr (HasMethodDeserialize<RawT, void, FArchive&>)
            Object.Deserialize(Ar);
        else if constexpr (IsMapType<T>)
        {
            if (Ar.Node.is_array())
            {
                for (int i = 0; i < Ar.Node.size(); i++)
                {
                    nlohmann::json& Node = Ar.Node[i];
                    if (Node.contains("key") && Node.contains("value"))
                    {
                        using TKey = typename T::key_type;
                        using TValue = typename T::mapped_type;
                        TKey key = TKey();
                        TValue value = TValue();
                        FArchive local_Ar_key(Node["key"], Ar);
                        TStaticSerializer<TKey>::Deserialize(key, local_Ar_key);
                        FArchive local_Ar_value(Node["value"], Ar);
                        TStaticSerializer<TValue>::Deserialize(value, local_Ar_value);
                        Object[key] = value;
                    }
                }
            }
        }
        else if constexpr (IsRangeContainerType<T>)
        {
            if (Ar.Node.is_array())
            {
                if constexpr (HasMethodResize<T>)
                    Object.resize(Ar.Node.size());
                for (int i = 0; i < Object.size(); i++)
                {
                    FArchive local_Ar(Ar.Node[i], Ar);
                    TStaticSerializer<typename T::value_type>::Deserialize(Object[i], local_Ar);
                }
            }
        }
        else if constexpr (IsSetType<T>)
        {
            if (Ar.Node.is_array())
            {
                for (int i = 0; i < Ar.Node.size(); i++)
                {
                    using TKey = typename T::key_type;
                    nlohmann::json& Node = Ar.Node[i];
                    TKey key = TKey();
                    FArchive local_Ar(Node, Ar);
                    TStaticSerializer<TKey>::Deserialize(key, local_Ar);
                    Object.insert(key);
                }
            }
        }
        else
        {
            Object = Ar.Node.get<RawT>();
        }
    }
};

template<>
class TStaticSerializer<FBinaryBuffer>
{
public:
    static void Serialize(FBinaryBuffer &Object, FArchive& Ar) 
    { 
        if (Object.BufferSize && Object.Buffer)
        {
            Ar.Node["BufferSize"] = Object.BufferSize;
            Ar.OutBuffers.push_back(FArchiveBuffer(Ar.Node, Object));
        }
    }
    static void Deserialize(FBinaryBuffer &Object, FArchive& Ar) 
    { 
        if (Ar.Node.contains("BufferOffset") && Ar.Node.contains("BufferSize"))
        {
            size_t BufferOffset = Ar.Node["BufferOffset"].get<size_t>();
            Object.BufferSize = Ar.Node["BufferSize"].get<size_t>();
            Object.Buffer = std::make_shared<unsigned char[]>(Object.BufferSize);
            std::copy(
                Ar.InBuffer.get()+BufferOffset, 
                Ar.InBuffer.get()+BufferOffset+Object.BufferSize, 
                Object.Buffer.get());
        }
    }
};
#endif

}