#pragma once
#include <queue>
#include <string>
#include <UDRefl/UDRefl.hpp>
#include <json/json.hpp>
#include <magic_enum/magic_enum_utility.hpp>
#include <base64.h>
#include "Object.h"
#include "Common/Math/Maths.h"

namespace nilou {

class FProperty;
class NPackage;

enum class EClassFlags
{
	None				  = 0x00000000u,
    /** Class is a native class - native interfaces will have CLASS_Native set, but not RF_MarkAsNative */
    Native                = 0x00000080u,
    /** Class was declared directly in C++ and has no boilerplate generated by UnrealHeaderTool */
    Intrinsic             = 0x10000000u,
};
ENUM_CLASS_FLAGS(EClassFlags);

enum class EMetaClass { Struct, Object, Enum };

#define BEGIN_CLASS_REGISTRY_INTERNAL(MetaClass, ClassName, Super, ClassFlags) \
    NClass* ClassName::Z_StaticClass = nullptr; \
    template<> \
    struct TClassRegistry<ClassName> : public FClassRegistryBase \
    { \
        using TClass = ClassName; \
        TClassRegistry<ClassName>() : FClassRegistryBase( \
            EMetaClass::MetaClass, \
            #ClassName, \
            Super::StaticClass(), \
            sizeof(ClassName), \
            ClassFlags, \
            [](void* Memory){ new (Memory) ClassName(); }) \
        { \
            TClass::Z_StaticClass = this->Class;

#define BEGIN_CLASS_REGISTRY(ClassName, Super, ClassFlags) \
    BEGIN_CLASS_REGISTRY_INTERNAL(Object, ClassName, Super, ClassFlags)

#define BEGIN_STRUCT_REGISTRY(ClassName, Super, ClassFlags) \
    BEGIN_CLASS_REGISTRY_INTERNAL(Struct, ClassName, Super, ClassFlags)


#define CLASS_PROPERTY(PropertyName) \
            AddProperty(#PropertyName, &TClass::PropertyName);

#define STRUCT_PROPERTY(PropertyName) CLASS_PROPERTY(PropertyName)

#define END_CLASS_REGISTRY(ClassName) \
        } \
    }; \
    TClassRegistry<ClassName> PREPROCESSOR_JOIN(ClassRegistry, __LINE__);

#define END_STRUCT_REGISTRY(ClassName) END_CLASS_REGISTRY(ClassName)

#define BEGIN_ENUM_REGISTRY(EnumName, ClassFlags) \
    NClass* StaticEnum_##EnumName = nullptr; \
    template<> \
    struct TClassRegistry<EnumName> : public FClassRegistryBase \
    { \
        using TEnum = EnumName; \
        TClassRegistry<EnumName>() : FClassRegistryBase( \
            EMetaClass::Enum, \
            #EnumName, \
            nullptr, \
            sizeof(EnumName), \
            ClassFlags, \
            [](void* Memory){ new (Memory) EnumName(); }) \
        { \
            StaticEnum_##EnumName = this->Class;

#define ENUM_VALUE(Value) \
            this->Class->EnumNames.Add({#Value, static_cast<int64>(TEnum::Value)});

#define END_ENUM_REGISTRY(EnumName) \
        } \
    }; \
    template<> NClass* StaticEnum<EnumName>() { return StaticEnum_##EnumName; } \
    TClassRegistry<EnumName> PREPROCESSOR_JOIN(ClassRegistry, __LINE__);

class NClass : public NObject
{
private:
    template<typename T> 
    friend class TClassRegistry;
    friend class FClassRegistryBase;
    static NClass* Z_StaticClass;
public:
    static NClass *StaticClass() { return Z_StaticClass; }
public:
    friend class FStructProperty;
    friend class FObjectProperty;
    friend class FEnumProperty;
    friend void InitUObject();

    NClass() = default;

    bool IsChildOf(const NClass *BaseClass) const
    {
        if (BaseClass == nullptr)
        {
            return false;
        }
        bool bResult = false;
        for (const NClass* Temp = this; Temp; Temp = Temp->GetSuperStruct())
        {
            if (Temp == BaseClass)
            {
                bResult = true;
                break;
            }
        }
        return bResult;
    }

    TArray<FProperty*> GetProperties(bool bIncludeSuper) const;

    void SerializeTaggedProperties(FArchive& Ar, void* Data) const;

    bool IdenticalProperties(const void* A, const void* B) const;

    NClass* GetSuperStruct() const
    {
        return SuperStruct;
    }

    NObject* CreateObject(const std::string& Name, NObject* Outer, EObjectFlags Flags=EObjectFlags::NoFlags) const;

    void SetClassFlags(EClassFlags FlagsToAdd)
    {
        EClassFlags OldFlags = EClassFlags::None;
        EClassFlags NewFlags = EClassFlags::None;
        do 
        {
            NewFlags = OldFlags | FlagsToAdd;
        }
        while( !ClassFlags.compare_exchange_weak(OldFlags, NewFlags) );
    }

    void ClearClassFlags(EClassFlags FlagsToClear)
    {
        EClassFlags OldFlags = EClassFlags::None;
        EClassFlags NewFlags = EClassFlags::None;
        do 
        {
            NewFlags = OldFlags & (~FlagsToClear);
        }
        while( !ClassFlags.compare_exchange_weak(OldFlags, NewFlags) );
    }

    bool HasAnyClassFlags(EClassFlags FlagsToCheck) const
    {
        return (ClassFlags & FlagsToCheck) != EClassFlags::None;
    }

    bool HasAllClassFlags(EClassFlags FlagsToCheck) const
    {
        return (ClassFlags & FlagsToCheck) == FlagsToCheck;
    }

    NObject* GetDefaultObject() const;
    template <typename T>
    T* GetDefaultObject() const { return Cast<T>(GetDefaultObject()); }

    int64 GetValueByNameString(const std::string& Name) const;
    std::string GetNameStringByValue(int64 Value) const;

protected:
    void CreateDefaultObject();

private:

    int32 Size;

    EMetaClass MetaClass;

    std::atomic<EClassFlags> ClassFlags;

    NClass* SuperStruct = nullptr;

    TArray<FProperty*> Properties;

	TArray<std::pair<std::string, int64>> EnumNames;

    std::function<void(void*)> ClassConstructor;

    NObject* ClassDefaultObject;

};

template <typename T> NClass* StaticEnum();

}