set_xmakever("3.0.0")
set_project("Nilou")

engine_version = "0.1.0"
add_rules("plugin.compile_commands.autoupdate", { outputdir = ".vscode" })

add_rules("mode.release", "mode.debug")
set_runtimes("MD")
if (is_os("windows")) then 
    add_defines("_CRT_SECURE_NO_WARNINGS")
end
-- TODO use xmake package manager
-- add_requires("vcpkg::gdal", {configs = {shared = true}})
-- add_requires("vcpkg::glfw3")
-- add_requires("glfw")
-- add_requires("imgui[glfw-binding,opengl3-binding,vulkan-binding]", { alias = "imgui" })
add_requires("imgui", {configs = {glfw = true, opengl3 = true, vulkan = true}})
-- add_requires("draco")
add_requires("fmt")
-- add_requires("vcpkg::llvm")
add_requireconfs("*", {external = false})

includes("xmake/module_rules.lua")
includes("xmake/target_rules.lua")
includes("Engine/Source/ThirdParty/clang-c/xmake.lua")
includes("Engine/Source/ThirdParty/glfw/xmake.lua")
includes("Engine/Source/Programs/NilouHeaderTool/xmake.lua")
includes("Engine/Source/ThirdParty/base64/xmake.lua")
includes("Engine/Source/ThirdParty/crossguid/xmake.lua")
includes("Engine/Source/ThirdParty/glad/xmake.lua")
includes("Engine/Source/ThirdParty/vulkan/xmake.lua")
includes("Engine/Source/ThirdParty/microprofile/xmake.lua")
includes("Engine/Source/ThirdParty/stb_image/xmake.lua")
includes("Engine/Source/ThirdParty/tinygltf/xmake.lua")
includes("Engine/Source/ThirdParty/headeronlys/xmake.lua")
includes("Engine/Source/ThirdParty/tiny3dtiles/xmake.lua")
includes("Engine/Source/Runtime/Core/xmake.lua")
includes("Engine/Source/Runtime/CoreUObject/xmake.lua")
includes("Engine/Source/Runtime/RHI/xmake.lua")
includes("Engine/Source/Runtime/RenderCore/xmake.lua")
includes("Engine/Source/Runtime/Engine/xmake.lua")
includes("Engine/Source/Runtime/VulkanRHI/xmake.lua")
includes("Engine/Source/Runtime/Launch/xmake.lua")
includes("Engine/Source/Runtime/xmake.lua")