implementing LightingPassPixelShader;

// float3 earth_center = float3(0.0f, 0.0f, -ATMOSPHERE.bottom_radius);

// Texture2D<float4> TransmittanceLUT        : register(t51);
// SamplerState      TransmittanceLUTSampler : register(s51);
// Texture3D<float4> ScatteringRayleighLUT        : register(t52);
// SamplerState      ScatteringRayleighLUTSampler : register(s52);
// Texture3D<float4> ScatteringMieLUT        : register(t53);
// SamplerState      ScatteringMieLUTSampler : register(s53);
