const int WATER_SCATTERING_TEXTURE_R_SIZE = 128;
const int WATER_SCATTERING_TEXTURE_MU_SIZE = 128;
const int WATER_SCATTERING_TEXTURE_MU_S_SIZE = 32;
const int WATER_SCATTERING_TEXTURE_NU_SIZE = 8;

const int WATER_SCATTERING_TEXTURE_WIDTH =
    WATER_SCATTERING_TEXTURE_NU_SIZE * WATER_SCATTERING_TEXTURE_MU_S_SIZE;
const int WATER_SCATTERING_TEXTURE_HEIGHT = WATER_SCATTERING_TEXTURE_MU_SIZE;
const int WATER_SCATTERING_TEXTURE_DEPTH = WATER_SCATTERING_TEXTURE_R_SIZE;

const float MAX_WATER_OPTICAL_DEPTH = 200; // meter

const int NUM_SCATTERING_ORDERS = 4;